version: '3'

services:
  ecommerce:
    build:
      context: .
      dockerfile: Dockerfile
    command: python code/manage.py runserver 0.0.0.0:8002
    ports:
      - "8123:8002"
    volumes:
      - .:/proj

  ecommerce-db:
    hostname: ecommerce-db
    image: postgres:14.11
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "1234:5432"

  ecommerce-order-db:
    image: postgres:14.11
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "1235:5432"

  ecommerce-redis:
    image: redis:7.0-alpine
    ports:
      - "5656:6379"
