# Generated by Django 5.0 on 2024-03-14 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_city_country_address_city_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField()),
                ('city_name', models.CharField()),
                ('country_name', models.CharField()),
            ],
        ),
        migrations.RemoveField(
            model_name='city',
            name='name',
        ),
        migrations.AddField(
            model_name='city',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='city',
            name='name_kz',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='city',
            name='name_ru',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='iata_code',
            field=models.CharField(blank=True, db_index=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='iso_code',
            field=models.CharField(blank=True, db_index=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='name_kz',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='name_ru',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
