# Generated by Django 5.0 on 2024-02-20 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name_plural': 'Товары заказа'},
        ),
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.CharField(max_length=8, unique=True, verbose_name='number'),
        ),
    ]
